### PR TITLE
Use readline

### PR DESCRIPTION
**Pull request by knqyf263**
Close https://github.com/knqyf263/pet/issues/10

### CODE REVIEW

**Comment by xinsnake** [comment]
@knqyf263   I think it works great on Linux (and I assume on Mac too). I tested on Windows with a PowerShell session which is a little bit strange. Screencast attached.

peek 2017-03-19 19-55

**Comment by knqyf263** [comment]
@xinsnake Thanks for your test!
You are right. I test only on `cmd.exe`...
Hmm... I wonder why the background color changes.

**Comment by xinsnake** [comment]
@knqyf263  My guest is that the dark colour may be hard-coded in the upstream library you use :smile:, just a guess. Don't worry it's good enough for now and hope someone will get it fixed someday. Thanks again for your hard-work getting this working.

**Comment by knqyf263** [comment]
@xinsnake Thanks!
I asked the developer of `readline`.
I will wait for a reply.

**Pull request merged**
